volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true
services:
  fastapi:
    environment:
      SIGNING_KEY: 5381f72f4a53f99b9691525252be57ac657fe166f45afdd8a46bf9737d8a92f4eb6450a0a1e69dc3586addb8f0c3f35b9b10e4972967bbd142698329a1bed931
      DATABASE_URL: postgresql://example_user:secret@postgres/example_db
      CORS_HOST: http://localhost:3000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}

  postgres:
    build:
      context: data
      dockerfile: Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: example_user
      POSTGRES_DB: example_db
    ports:
      - 15432:5432

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ok@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ok
      PGADMIN_DISABLE_POSTFIX: 1
    depends_on:
      - postgres
